name: Makefile CI

on:
  push:
    branches: [ stable ]
  pull_request:
    branches: [ stable ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Clone Github Repo Action
      uses: GuillaumeFalourd/clone-github-repo-action@v1
      with:
        # Repository Owner
        owner: 'VisorFolks'
        # Repository name
        repository: 'avr-toolchain'
        # PAT with repository scope (https://github.com/settings/tokens)
        access-token: ${{ secrets.CI_PAT }}
    - name: Install Dependencies
      run: sudo apt install cppcheck tree -y
      
    - name: Move Toolchain
      run: |
        mkdir -p toolchain
        sudo mv $(pwd)/avr-toolchain ./toolchain/
        sudo chmod +x -R ./toolchain/
        sudo chown -R runner:docker ./toolchain/
        
    - name: Build AVR
      run: sudo make demo_avr
